title: lahdeero homepage
description: "Page is better than no page"
author:
  name: "Eero"
  email: "eero at gmail.com"
  url: "https://lahdeero.github.io/"

baseurl: /

source: .
destination: ./_site
permalink: /:title
paginate: 3
paginate_path: /page/:num/

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

future: true
plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-sitemap

# Custom variables
owner : "lahdeero"
year : "2020"
